name: Deploy automático para VPS Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via SSH na VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 191.101.2.230
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user/htdocs/srv888225.hstgr.cloud
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear

